// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuX1o4MrRfacN4sQ_TMYrMl7PZXydQni4',
    appId: '1:380243513330:web:13d8bb20cd82bace0e656b',
    messagingSenderId: '380243513330',
    projectId: 'daidai-rhing',
    authDomain: 'daidai-rhing.firebaseapp.com',
    storageBucket: 'daidai-rhing.firebasestorage.app',
    measurementId: 'G-QV66GTTWPT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvO91qP3h5sidSHB6sYIOjpc8DaaYexOg',
    appId: '1:380243513330:android:6dd1974572756b100e656b',
    messagingSenderId: '380243513330',
    projectId: 'daidai-rhing',
    storageBucket: 'daidai-rhing.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5K_GS2_4lfV93F6ZCK8GhvhzicWcV9wU',
    appId: '1:380243513330:ios:48fc855da8b1260f0e656b',
    messagingSenderId: '380243513330',
    projectId: 'daidai-rhing',
    storageBucket: 'daidai-rhing.firebasestorage.app',
    iosBundleId: 'jp.rhing.daidai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5K_GS2_4lfV93F6ZCK8GhvhzicWcV9wU',
    appId: '1:380243513330:ios:48fc855da8b1260f0e656b',
    messagingSenderId: '380243513330',
    projectId: 'daidai-rhing',
    storageBucket: 'daidai-rhing.firebasestorage.app',
    iosBundleId: 'jp.rhing.daidai',
  );
}
